name: Build docker image

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

env:
  REGISTRY_URL: ghcr.io
  REGISTRY_USERNAME: andgrigkhai
  SERVICE_NAME: argocd/app:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to docker registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set version
        id: version
        run: |
          ver="$(date +%Y%m%d%H%M)"
          echo "version=$ver" >> $GITHUB_OUTPUT
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push docker containers
        uses: docker/build-push-action@v5
        with:
          context: src
          file: src/Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ env.REGISTRY_URL }}/${{ env.REGISTRY_USERNAME }}/${{ env.SERVICE_NAME }}:${{ steps.version.outputs.version }}
            ${{ env.REGISTRY_URL }}/${{ env.REGISTRY_USERNAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
            ${{ env.REGISTRY_URL }}/${{ env.REGISTRY_USERNAME }}/${{ env.SERVICE_NAME }}:latest

      - name: Checkout charts repository
        uses: actions/checkout@v4
        with:
          repository: andgrigkhai/charts
          path: charts
          token: ${{ secrets.GH_TOKEN }}
      - name: Update image version in the related chart values
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'lab-argo/values.yaml'
          repository: andgrigkhai/charts
          branch: main
          message: 'Update Image Version to ${{ steps.version.outputs.tag }}'
          token: ${{ secrets.GH_TOKEN }}
          workDir: charts
          changes: |
            {
              "lab-argo/values.yaml": {
                "image.tag": "${{ steps.version.outputs.version }}"
              },
              "lab-argo/Chart.yaml": {
                "appVersion": "${{ steps.version.outputs.version }}"
              }
            }
